#!/usr/bin/env bash
# set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"

# display env variables for debugging
echo "Environment variables:"
echo "APP_DATA_DIR=$APP_DATA_DIR"